"""The staff board reads the SAME day as the schedule board. This pulls every
appointment the day board shows on the ten sheet modalities, plus the techs' own
IV / lab work, out of schedule.html and writes assets/staff-data.js.

Run after genboard: python3 tools/genstaff.py"""
import re, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ROW, OPEN = 96, 6            # genboard.py: px per hour, opening hour

# platform column id -> sheet modality (Cassandra's "Certified Yes/No" names)
COL2MOD = {
    'redlight': 'RedLight', 'erchonialaser': 'Erchonia Laser',
    'nanotubroom': 'Nano Bath 1', 'adananotubroom': 'Nano Bath 2',
    'saltroom': 'Halo Therapy', 'biocharger': 'Bio Charger', 'bemer': 'Bemer',
    'hydrogeninhalation': 'Hydrogen Inhalation',
    'nanovi1': 'Nano Vie', 'nanovi2': 'Nano Vie', 'rife': 'RIFE',
}
# the techs on the sheet are the nurses / medic / MA the platform already has
TECH_COL = {'Nick': 'nurseiv1', 'Juan': 'nurseiv2', 'Bea': 'mediciv', 'Wes': 'labdraw'}

APPT = re.compile(r'<div class="cal-appt (?P<cls>[^"]*)" style="top:(?P<top>\d+)px;height:(?P<h>\d+)px"(?P<attrs>[^>]*)>')
ATTR = re.compile(r'data-([a-z]+)="([^"]*)"')

def parse():
    html = (ROOT / 'schedule.html').read_text()
    day = html[html.index('id="l-day"') if 'id="l-day"' in html else 0:]
    out = []
    for m in APPT.finditer(day):
        if 'is-elsewhere' in m.group('cls'): continue
        a = dict(ATTR.findall(m.group('attrs')))
        col = a.get('col')
        if col not in COL2MOD and col not in TECH_COL.values(): continue
        top, h = int(m.group('top')), int(m.group('h'))
        at = OPEN * 60 + round(top * 60 / ROW)
        mins = round((h + 2) * 60 / ROW)
        out.append({'id': a.get('appt'), 'col': col, 'pt': a.get('pt'), 'at': at, 'mins': mins,
                    'tx': a.get('tx'), 'st': a.get('st')})
    return out

def main():
    appts = parse()
    seen = set(); uniq = []
    for a in appts:
        k = (a['col'], a['at'])
        if k in seen: continue
        seen.add(k); uniq.append(a)
    tx = [dict(a, mod=COL2MOD[a['col']]) for a in uniq if a['col'] in COL2MOD]
    work = {n: [a for a in uniq if a['col'] == c] for n, c in TECH_COL.items()}
    names = {}
    for m in re.finditer(r'daycal-col-head" data-col="([a-z0-9]+)"[^>]*>([^<]+)<', (ROOT/'schedule.html').read_text()):
        names[m.group(1)] = m.group(2).strip()
    data = {'date': 'Tuesday, July 21', 'cols': COL2MOD, 'names': names, 'techCol': TECH_COL,
            'appts': sorted(tx, key=lambda a: (a['at'], a['col'])), 'work': work}
    js = ('/* GENERATED by tools/genstaff.py from schedule.html — the staff board and the booking\n'
          '   gate read the same day the schedule shows. Do not edit by hand. */\n'
          'window.STAFF_DATA = ' + json.dumps(data, indent=1) + ';\n')
    (ROOT / 'assets' / 'staff-data.js').write_text(js)
    print('staff-data.js:', len(tx), 'treatments on the sheet modalities;',
          {n: len(v) for n, v in work.items()}, 'own appointments per tech')

if __name__ == '__main__':
    main()
